In [10]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
dataset = pd.read_csv('datasets/campaign_data.csv')
dataset

CampaignID  GoalAmount   RaisedAmount  DurationDays  NumBackers  \
0      CID_00000       76159   73518.028955            15        1903   
1      CID_00001       69394   60068.683288            49         469   
2      CID_00002       18652   22958.153470            58         148   
3      CID_00003       19487   24229.048390            39         780   
4      CID_00004       26734   17984.630311            68        1622   
...          ...         ...            ...           ...         ...   
99995  CID_99995       80417  112068.932642            26         870   
99996  CID_99996       85052  100430.502040            78        1146   
99997  CID_99997       68407  102020.936312            87         636   
99998  CID_99998       59749   67026.111706            51        1276   
99999  CID_99999       39913   54863.288105            73         695   

      Category LaunchMonth    Country Currency  OwnerExperience VideoIncluded  \
0         Film   September  Australia      GBP               11           Yes   
1          Art     October  Australia      GBP                7           Yes   
2         Film    February        USA      EUR               17            No   
3         Film     October    Germany      AUD               10            No   
4        Games   September  Australia      AUD               12           Yes   
...        ...         ...        ...      ...              ...           ...   
99995    Music     October         UK      AUD                6            No   
99996     Film     October        USA      USD                8            No   
99997      Art       March         UK      EUR                2           Yes   
99998    Music      August  Australia      CAD               10           Yes   
99999     Film       April    Germany      CAD               11            No   

       SocialMediaPresence  NumUpdates  IsSuccessful  
0                    41758           3             0  
1                    79112          48             0  
2                     3942           9             1  
3                    22047          35             1  
4                    72568          17             0  
...                    ...         ...           ...  
99995                84173           8             1  
99996                13913          42             1  
99997                45273          13             1  
99998                67574          29             1  
99999                84806          41             1  

[100000 rows x 14 columns]

In [11]:
x = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values

In [12]:
y

array([1903,  469,  148, ...,  636, 1276,  695])

In [13]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25)

In [14]:
xtrain

array([[6.21808826e+04, 6.10000000e+01],
       [6.69586242e+04, 2.70000000e+01],
       [2.39189974e+04, 8.90000000e+01],
       ...,
       [4.87887715e+04, 2.10000000e+01],
       [4.64399498e+04, 2.70000000e+01],
       [7.48619108e+04, 6.00000000e+01]])

In [15]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

print (xtrain[0:10, :])
print (xtest[0:10, :])

[[ 0.34707844  0.41200269]
 [ 0.49057547 -1.1598679 ]
 [-0.80209772  1.70648436]
 [ 0.07141116  1.38286394]
 [-0.02091865  0.36577121]
 [-1.183447    1.70648436]
 [-1.13474246  0.92054906]
 [-0.78127783 -1.48348832]
 [-0.50623954 -0.46639558]
 [-0.61512046  1.70648436]]
[[ 1.80134704  1.66025287]
 [-1.28362423  0.13461376]
 [ 1.83831545  1.1517065 ]
 [-1.43596109 -1.34479385]
 [ 0.7375802   1.42909543]
 [-0.84231608  1.05924353]
 [ 0.19798432  1.42909543]
 [ 1.44608636  0.55069716]
 [ 2.046601    1.29040097]
 [ 2.44801877 -0.14277516]]


In [24]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 42)
classifier.fit(xtrain, ytrain)

LogisticRegression(random_state=42)

In [25]:
y_pred = classifier.predict(xtest)
y_pred

array([  14, 1477,   14, ...,  760,   14,  660])

In [26]:
import pickle
with open('Logistic_model.pkl', 'wb') as files:
    pickle.dump(classifier, files)

with open('Logistic_model.pkl' , 'rb') as f:
    classifier = pickle.load(f)

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest, y_pred)
print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [28]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(ytest, y_pred))

Accuracy :  0.00044


In [29]:
from sklearn import datasets

In [30]:
import pandas as pd
data= pd.read_csv('datasets/campaign_data.csv')
data.head()

CampaignID  GoalAmount  RaisedAmount  DurationDays  NumBackers Category  \
0  CID_00000       76159  73518.028955            15        1903     Film   
1  CID_00001       69394  60068.683288            49         469      Art   
2  CID_00002       18652  22958.153470            58         148     Film   
3  CID_00003       19487  24229.048390            39         780     Film   
4  CID_00004       26734  17984.630311            68        1622    Games   

  LaunchMonth    Country Currency  OwnerExperience VideoIncluded  \
0   September  Australia      GBP               11           Yes   
1     October  Australia      GBP                7           Yes   
2    February        USA      EUR               17            No   
3     October    Germany      AUD               10            No   
4   September  Australia      AUD               12           Yes   

   SocialMediaPresence  NumUpdates  IsSuccessful  
0                41758           3             0  
1                79112          48             0  
2                 3942           9             1  
3                22047          35             1  
4                72568          17             0

In [31]:
from sklearn.model_selection import train_test_split
X=data[['GoalAmount', 'RaisedAmount', 'DurationDays', 'NumBackers']]
y=data['IsSuccessful']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [32]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [33]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9953333333333333
